# Generated by Django 5.0.3 on 2024-03-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.PositiveIntegerField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
